unique_ids:
  forms: {}
  modules: {}
  server_modules: {}
  assets:
    single-column.html: PDJANGE437Q2U3QU3Y5L2FASJWHTRYMD
    dashboard.html: YG5RMEKIAVKQQO5EQ2EQ7PLZ2DTDYAEA
    theme.css: SF6VDO4AHCJ2B24ST3OVGUG2CD7EX2ZB
